### PR TITLE
Allow users to manually set their timezone

### PR DESCRIPTION
**Pull request by gucci-on-fleek**
This PR should (hopefully) be equivalent to the patch that @kberry attached in #14.

Please let me know if you have any feedback.

### CODE REVIEW

**Comment by pauloney** [comment]
Max, how many time-zones are you supposed to get (to choose from) when you press the button? All 37 in the world?
PN

**Comment by gucci-on-fleek** [comment]
It's showing 595 different time zones for me. It's not a drop down though, it's a free-form text entry that autocompletes to any of the standard "tz"/"IANA" time zones.

**Comment by pauloney** [comment]
I see it now. I am just wondering if there is a way (easy) to restrict to
the 37 standard TZs and if that would be easier for the users.

In this way it work fantastically well and it is exactly what Karl wants
... just not easy for the users...

Paulo Ney

**Comment by gucci-on-fleek** [comment]
> I am just wondering if there is a way (easy) to restrict to
> the 37 standard TZs and if that would be easier for the users.

There are only 37 UTC offsets that are used, but there are far more timezone names than that. Daylight saving/summer time is the main complication here. 

Using Canada as an example, there are 6 "main" timezones (Pacific, Mountain, Central, Eastern, Atlantic, and Newfoundland), but there are a bunch of weird DST edge cases that actually lead to there being 10 different time zones. [Wikipedia](https://en.wikipedia.org/wiki/Time_in_Canada)

The standard "tz" database is certainly larger than necessary, but [Microsoft's list of zones](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11))—which is the only other complete database that I'm aware of—has 76 entries. We could use this if you prefer, but I think that a dropdown menu with 76 entries is probably harder to use than what I have now.

We probably don't need to worry about any weird Daylight Saving Time stuff or islands with only a few hundred people; however, I'm still not able to find any appropriate lists that cover the entire world and have ~40 entries. If you do find such a list though, let me know and I can use it here instead.

**Comment by pauloney** [comment]
Cool! Let's experiment with the way you set and let's gauge what people
prefer ... Many thanks.

Paulo Ney

**Comment by pauloney** [comment]
Karl, Max, (the order of the two names is not intentional, it is alphabetical)

Yoni placed an X before the Triangle on the input box. In this way someone that is baffled by why they are getting -- an option of one-item -- when clicking a supposedely drop-down menu, can at least try the X and they will see that the filed is editable.

You can see it on the current page:

           https://tug.org/tug2022/program.html

Paulo Ney

**Comment by gucci-on-fleek** [comment]
> Yoni placed an X before the Triangle on the input box.

This is _very_ browser dependant. Desktop Chrome and Mobile Chrome show the X and the triangle; desktop Firefox shows neither an X nor a triangle, but opens up a drop down when you click in the text box; and mobile Firefox treats it like a plain text box, never showing a drop down no matter what you do. I don't have any way to test with Safari here, although it would be helpful if someone could.

Chrome + Edge is 80% of desktop browsers, while Firefox and Safari are each about 10%. Chrome is 70% of mobile browsers, Safari is 25%, and Firefox is 0.5% [(Source)](https://gs.statcounter.com/browser-market-share). So I'd say that this seems fine since the only browser where the current implementation is somewhat-unusable has 0.5% market share, although we may need to change something if Safari has issues here.

**Comment by yoniros** [comment]
Yea, you are right, and thanks for testing.
On my end, I tested only on Mac, using Chrome & Safari. On both, the 'X' icon shows up.

I also just viewed it on iPhone (Safari) and noticed that layout is not so great. The dropdown is too wide for the phone (I have increased its width in my change, and have not tested on mobile). We may need to decrease it a bit or make some changes so that it looks better on mobile.

**Comment by gucci-on-fleek** [comment]
> On my end, I tested only on Mac, using Chrome & Safari. On both, the 'X' icon shows up.

Ok, that's good. Only Firefox is being weird here.

> We may need to decrease it a bit or make some changes so that it looks better on mobile.

Something like this maybe? (untested)

```diff
--- a/program.css
+++ b/program.css
 #yourTimeZone {
-  width: 250px;
+  width: min(250px, 90vw);
 }

**Comment by yoniros** [comment]
This seems to work well:

```css
#yourTimeZone {
  width: min(250px, 100%);
}
```

I tested with iPhone emulator on chrome (on mac).
Hopefully works the same on the real device.

**Comment by kberry** [comment]
https://tug.org/tug2022/program.html

I don't see any X's, or triangles. Tried both Chrome and Firefox
(on GNU/Linux).

Other minor niglets I'm noticing today:

1) I think the period after the timezone field adds confusion, in this
case. (Looks like it might be some kind of control.) I suggest removing it.

2) The text:
  Current local time is 6:11:07 AM, as determined from your browser. All
  presentation times below are in time zone:

is no longer correct. Instead, I suggest:

  All times below are in time zone: ____
  Current time in that time zone: 6:11:07 AM

karl

**Comment by gucci-on-fleek** [comment]
@kberry 

> I don't see any X's, or triangles. Tried both Chrome and Firefox
(on GNU/Linux).

That's "expected" for Firefox (see https://github.com/TeXUsersGroup/TUG-Conference/pull/15#issuecomment-1241324661), but unexpected with Chrome. On my end in Chrome, I'm seeing the triangle and the X, but only when I click or hover on the text box. 

image

Does the triangle/arrow show up if you click/hover on the text box?

> 1) I think the period after the timezone field adds confusion, in this
> case. (Looks like it might be some kind of control.) I suggest removing it.
> 
> 2) The text:
>   Current local time is 6:11:07 AM, as determined from your browser. All
>   presentation times below are in time zone:
> 
> is no longer correct. Instead, I suggest:
> 
>   All times below are in time zone: ____
>   Current time in that time zone: 6:11:07 AM

Both of these suggestions look good to me.

**Comment by pauloney** [comment]
Hi Max, Hi Karl,

I showed the interface to a few people (5 only) and asked them to use it to
change their TZ on the browser... and the answer was, not surprisingly, none
of them were able to do it. Most of them interpreted the "triangle" as a
sign
of the pull down menu and were surprised to find a menu of one-item, and
did not take the step to "edit" the content inside the box.

Yoni suggested that a round-circle-with-an-X would probably be a better
option for an icon at the end together with the option to wipe the line out
and with most common searches (YouTube, Google, ....) and he is going
to look at it.

I do agree that this format is the best for the admins of the Conference,
but I am not sure that would apply to the attendees. We merged the code
and we probably should experiment with it a bit, to probably find some
appropriate text to help people deal with it.

It is now part of the current page.
Paulo Ney

**Comment by yoniros** [comment]
> All times below are in time zone: ____
> Current time in that time zone: 6:11:07 AM

Yea, I think this proposed text will make it clearer.

**Comment by kberry** [comment]
As you say, changing the tz is useful for admins, but I also don't think it's important that random viewers of the page know that the timezone can be changed. Thus I would not worry about any icons to try to indicate that (IMHO no icon will have that intuitive meaning, it's too obscure), or any text to describe the possibility. Surely there are more important things to work on.

My only thought is to change the text as I already suggested, as written in several comments here.

If you really insist on explicitly mentioning the possibility of changing the tz, I can give another idea. But I think it is better not to.

**Pull request merged**
